### ISSUE TITLE
Run in console error in 1.4.0

### ISSUE THREAD

**Issue by L0Lock** [Hasib345/Blender-Text-Editor-Essentials#6]
Run In Console (Ctrl R) gives an error in 1.4.0:

```
Python: Traceback (most recent call last):
  File "C:\AppInstall\Blender\MyScripts\addons\Blender-Text-Editor-Essentials\consol.py", line 94, in scrollback_append
    scrollback(c_dict, text=text, type=type)
  File "C:\AppInstall\Blender\stable\blender-4.0.0+stable.878f71061b8e\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\AppInstall\Blender\stable\blender-4.0.0+stable.878f71061b8e\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
```

**Comment by Hasib345** [comment]
I already fixed both issues in version 1.5 . I uploaded the version 1.5 in github . Thanks I am going to mark both issues complete
